DROP DATABASE IF EXISTS beerorder;
DROP USER IF EXISTS `BeerOrderAppId`@`%`;
CREATE DATABASE IF NOT EXISTS beerorder CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `BeerOrderAppId`@`%` IDENTIFIED WITH mysql_native_password BY 'eagles123';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `beerorder`.* TO `BeerOrderAppId`@`%`;
FLUSH PRIVILEGES;